INSERT INTO clientes (username, nombre, apellido, email, create_at) VALUES('a85','Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01');
INSERT INTO clientes (username, nombre, apellido, email, create_at) VALUES('j23','Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02');
INSERT INTO clientes (username, nombre, apellido, email, create_at) VALUES('l85','Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03');
INSERT INTO clientes (username, nombre, apellido, email, create_at) VALUES('r55','Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04');
INSERT INTO clientes (username,nombre, apellido, email, create_at) VALUES('E85','Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01');
INSERT INTO clientes (username,nombre, apellido, email, create_at) VALUES('r85','Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10');
INSERT INTO clientes (username,nombre, apellido, email, create_at) VALUES('R985','Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18');
INSERT INTO clientes (username,nombre, apellido, email, create_at) VALUES('J185','John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28');
INSERT INTO clientes (username,nombre, apellido, email, create_at) VALUES('D85','Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03');
INSERT INTO clientes (username,nombre, apellido, email, create_at) VALUES('M85','Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04');
INSERT INTO clientes (username,nombre, apellido, email, create_at) VALUES('T65','Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05');
INSERT INTO clientes (username,nombre, apellido, email, create_at) VALUES('Eva','Eva', 'Ortiz', 'evamariaob76@gmail.com', '2018-03-06');
INSERT INTO clientes (username,nombre, apellido, email, create_at) VALUES('Sebas','Martín', 'Sebastián', 'sebas.roe@gmail.com', '2018-03-05');


INSERT INTO `usuarios` (username, password, enabled, nombre, apellido, email) VALUES ('andres','$2a$10$C3Uln5uqnzx/GswADURJGOIdBqYrly9731fnwKDaUdBkt/M3qvtLq',1, 'Andres', 'Guzman','profesor@bolsadeideas.com');
INSERT INTO `usuarios` (username, password, enabled, nombre, apellido, email, img, foto_portada, descripcion, bio) VALUES ('admin','$2a$10$RmdEsvEfhI7Rcm9f/uZXPebZVCcPC7ZXZwV51efAvMAp1rIaRAfPK',1, 'Eva', 'Ortiz','del19al21@gmail.com','imagen.jpg','5madrid.jpg','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,');

INSERT INTO `comercios` ( `visitas`,`likes`,`actividad`, `aparicion`, `cp`, `create_at`, `direccion`, `facebook`, `lat`, `lng`, `nombre`, `parrafo_one`,  `resumen`, `telefono`,`img`,`img1`,`img2`,`parrafo_two`) VALUES ('1','1','hoteles', '1610', '28012 Madrid', '2019-08-01', 'Calle de Postas, 17', 'https://www.facebook.com/pages/Farmacia-Deleuze-Isasi/171909589510209', '40.415701', '-3.705847', 'Hotel Petit Palace Posada del Peine', 'Hace ya más de 400 años que Juan Posada abre las puertas de esta fonda, situada estratégicamente junto a la Casa de Postas, principal parada de diligencias de la Villa (en esta época Madrid tenía un censo aproximado de 900 coches de caballos), a la que  llegaban granjeros y comerciantes con productos de las provincias que pernoctaban uno o dos días en la capital. Este alojamiento debe su nombre al característico peine atado a una cuerda, para impedir que los viajeros se lo llevaran, que se encontraba en cada una de sus habitaciones. Un lujo para la época, que le distinguió de los demás establecimientos, adoptando el mismo como emblema.', 'En pleno casco antiguo de la capital y junto a la Plaza Mayor de Madrid, se encuentra el Petit Palace Posada del Peine; un hotel ubicado en un espacio único con más de 400 años de historia que hacen de este hotel el más antiguo de España', '915238151','delPeine1.jpg','2elPeine1.jpg','2delPeine1.jpg','La posada permaneció cerrada entre 1960 y 2006, año en que volvió a abrirse totalmente rehabilitada en su interior pero conservando gran parte de su aspecto exterior. En uno de los más modestos ejemplos de la historia de la azulejería urbana en Madrid. El hotel –rebautizado como Petit Palace Posada del Peine– se compone de tres edificios unidos, con tres estilos arquitectónicos diferentes y de distintas épocas. Solo se han conservado las fachadas de los tres edificios originales, en las que todavía se puede ver escrito su nombre. Ha quedado noticia de que entre sus paredes se alojaron, entre otros, la viuda de Gustavo Adolfo Bécquer, Casta Esteban, o el pintor José Gutiérrez Solana. El edificio fue además objeto del discurso de ingreso en la Academia de la Lengua de Camilo José Cela');
INSERT INTO `comercios` ( `visitas`,`likes`,`actividad`, `aparicion`, `cp`, `create_at`, `direccion`, `facebook`, `lat`, `lng`, `nombre`, `parrafo_one`,  `resumen`, `telefono`,`img`,`img1`,`img2`,`parrafo_two`) VALUES ('5','2','farmacias', '1780', '28015 Madrid', '2019-09-01', 'Calle de San Bernardo, 39 ','https://www.facebook.com/pages/Farmacia-Deleuze-Isasi/171909589510209', '40.4235479', '-3.707570', 'Farmacia Deleuze', 'Abierta en 1780 con el nombre de Botica de San Bernardo, esta farmacia prodigiosa conserva su original decoración, sobre cuyo estilo hay tantas denominaciones como autores han opinado sobre ello. Digamos que el estilo predominante en la tienda sería el rococó, y el despacho interior obedecería al estilo historicista con elementos neogóticos y árabes. Su primer farmacéutico conocido es Baltasar de Riego, que era pintor además de farmacéutico. Aquí se reunían escritores como Espronceda y Ventura de la Vega.', 'En pleno casco antiguo de la capital y junto a la Plaza Mayor de Madrid, se encuentra el Petit Palace Posada del Peine; un hotel ubicado en un espacio único con más de 400 años de historia que hacen de este hotel el más antiguo de España','915420913','deleuze4.jpg','deleuze5.jpg','deleuze3.jpg','Después de visitar la farmacia más antigua de Madrid, vinculada directamente con la Familia Real, hoy vamos a conocer otra también muy antigua e interesante por varios motivos, ubicada en la calle San Bernardo, 39. Se trata de la Farmacia Deleuze.Aunque en su fachada aparece el año 1834, lo cierto es que los primeros documentos que hablan de su existencia son de mediados del siglo XVIII, de 1780, donde se ubica lo que primero fue “Botica de San Bernardo”. Entrar en este recinto es como hacer un pequeño viaje al pasado. Curiosamente, al igual que la Farmacia de la Reina Madre, esta botica fue también un lugar donde hombres de ciencia preparaban medicamentos y la clientela los encargaba y adquiría; al mismo tiempo fue un lugar habitual de escritores y centro de tertulias intelectuales y políticas.');
INSERT INTO `comercios` ( `visitas`,`likes`,`actividad`, `aparicion`, `cp`, `create_at`, `direccion`, `facebook`, `lat`, `lng`, `nombre`, `parrafo_one`,  `resumen`, `telefono`,`img`,`img1`,`img2`,`parrafo_two`) VALUES ('0','1','librerías', '1650', '28013 Madrid', '2019-10-01', 'Pasadizo de San Ginés, 2', 'https://www.facebook.com/Librer%C3%ADa-San-Gin%C3%A9s-110087389064491', '40.417145', ' -3.706704', 'Librería San Ginés','No es poca la historia que recoge este singular callejón o pasadizo, de apenas sesenta metros de longitud y que siempre fue peatonal debido a su poca anchura. .El pasadizo de San Ginés comienza en la calle del Arenal y termina en la plazuela con el nombre de ese santo, coincidiendo toda su fachada del lado derecho con el lateral de la iglesia de San Ginés de Arlés (s. XVII), cuyo arquitecto fue Juan Ruiz. ', 'Los libros que están a la venta son usados, en su gran mayoría en castellano, de historia, literatura, acción… con precios a partir de un euro. Los ejemplares más antiguos que tienen son del siglo XIX. Cuentan con un gran almacén e intentan ir cambiando los títulos todo lo que pueden.',  '913664686','sanGines1.jpg','sanGines4.jpg','sanGines5.jpg', 'Cada mañana Javier o Alicia Sanz, a veces ambos, sacan cientos de libros de la caseta de madera situada en el pasadizo de San Ginés para colocarlos cuidadosamente en los anaqueles. La misma operación se repite, 363 días al año, o lo que es lo mismo, todo el año excepto los días de Navidad y Año Nuevo. Estos hermanos continúan el trabajo de su padre Luis, que adquirió la legendaria librería en 1952 y en la que estuvo al frente sesenta años. Ya su abuelo regentaba un puesto de libros en la calle de Santa Engracia.');
INSERT INTO `comercios` ( `visitas`,`likes`,`actividad`, `aparicion`, `cp`, `create_at`, `direccion`, `facebook`, `lat`, `lng`, `nombre`, `parrafo_one`,  `resumen`, `telefono`,`img`,`img1`,`img2`,`parrafo_two`) VALUES ('2','4','restaurantes', '1725', '28005 Madrid', '2019-11-01', 'Calle de Cuchilleros, 17','https://www.facebook.com/RestauranteBotin/', ' 40.414197', ' -3.707917', 'Restaurante Sobrino de Botín ', 'Casa Botín, fundada en 1725, es el restaurante más antiguo del mundo según el Libro Guinness de los Records y uno de los referentes de la mejor cocina tradicional en Madrid.La revista Forbes le reservó el tercer puesto entre los 10 mejores restaurantes clásicos del mundo, a la Casa y a sus dos especialidades, los deliciosos cochinillos y corderos asados al estilo castellano.Tres y cuatro veces por semana llegan al restaurante cargamentos de los mejores cochinillos segovianos y corderos procedentes del triángulo mágico de esta carne: Sepúlveda-Aranda-Riaza.Poco a poco, lentamente, corderos y cochinillos se van dorando a los calores y la respiración pausada y solemne del viejo horno, alimentado con leña de encina. Un horno que ha permanecido en funcionamiento desde su fundación bajo la atenta mirada de los maestros horneros y los expertos cocineros que llevan toda la vida en la Casa.',  'Antonio González y José González heredaron el restaurante Sobrino de Botín (Cuchilleros, 17) de su padre,  que a su vez lo había heredado de su abuelo. Este se encargó de mantener todo como lo habían dejado los Botín, la familia francesa que le traspasó el negocio después de fundarlo en 1725 sobre una bodega del siglo XVII."', '913664686','sobreino2.jpg','sobreino4.jpg','sobreino3.jpg', 'Es cocina de autor, sí, pero que viene firmada por siglos de tradición, y que reverbera la esencia de las mejores materias primas, respetando, tal y como sostenía Gaudí, que la originalidad es volver a los orígenes.Nuestra misión es pues que las costumbres e historia de Madrid se sientan en cada bocado. Seguir inspirando a escritores y artistas, y que estos continúen sentando a sus personajes a nuestra mesa. Pero, sobre todo, queremos seguir conquistando el paladar y el alma de cada uno de nuestros comensales, con el mimo y cuidado que ponemos a cada plato y a nuestro servicio.Aunque aspiramos a servir en cada mesa el mejor cochinillo o cordero, no por eso se desdeñan y descuidan otros platos: también se puede degustar una buena merluza de pincho, lenguado fresco, las almejas Botín, la sopa castellana, el refrescante gazpacho y muchas otras delicias que vienen acompañadas de los mejores caldos.');
INSERT INTO `comercios` ( `visitas`,`likes`,`actividad`, `aparicion`, `cp`, `create_at`, `direccion`, `facebook`, `lat`, `lng`, `nombre`, `parrafo_one`,  `resumen`, `telefono`,`img`,`img1`,`img2`,`parrafo_two`) VALUES ('8','2','farmacias', '1578', '28013 Madrid', '2019-11-01', 'Calle Mayor, 59','https://www.facebook.com/pages/Real-Farmacia-de-la-Reina-Madre/1570787816585386', '40.415572', '-3.709762', 'Farmacia Reina Madre', 'Domina el espacio interior «un mostrador de caoba labrada con adornos de ángeles y una serie de dibujos geométricos», a partir de la decoración diseñada por Antonio Rosselló en 1914.2​ También llaman la atención los dos panales de azulejos obra de Juan Ruiz de Luna, señalando dos años: 1578, el de la fundación, y 1914, «fecha en la que se trasladó la farmacia desde la calle Sacramento hasta la calle Mayor».1​ En la primitiva estructura –que se mantiene intacta–,​ destacan los pequeños cajones de madera, «cada uno pertenecía a un cliente en los que se les guardaba su medicación hasta que venían a recogerla».De la colección de albarelos y botes de farmacia de distintas épocas destacan algunos ejemplares renacentistas. Se conserva asimismo «un frasco con polvo de extracto de momia que se usaba para la gangrena». En el sótano que sirve de almacén estuvo un pequeño museo, del que aún se conservan una caja registradora, primitivas básculas para pesar bebés, además de numerosas recetas de las sustancias de opiáceos o fórmulas magistrales de pomadas e ungüentos.',  'Al entrar en la farmacia del número 59 de la calle Mayor, entre el mercado de San Miguel y la Plaza de la Villa, un antiguo olor a madera nos recibe. Parece un local pequeño, nada que ver con la realidad porque en su interior esconde un antiguo laboratorio que hoy es testigo de una parte importante de la historia de Madrid.',  '913664686','ReinaMadre2.jpg','ReinaMadre3.jpg','ReinaMadre4.jpg',  'Algunos estudios asocian su posible origen a la botica que el alquimista veneciano de Felipe II de España tuvo en la calle del Sacramento,3​ y al interés del monarca en conseguir algún tipo de plata alquímica para costear sus gastos de guerra. En esa línea pseudo-histórica se da el dato de la inauguración de la botica un 15 de mayo de 1578 (según publicaba sin demasiado fundamento La Correspondencia de España en sus números del 13 y el 15 de octubre de 1874). Legendario parece asimismo el dato de que se hiciera famosa por fabricar la pomada facial relajante usada por la Farnesio, abrumada al parecer «por los disgustos de sus nueras».1Durante el siglo xix se hicieron famosas las tertulias reunidas en el antiguo local, reuniendo a liberales, progresistas y republicanos, entre los que pudo estar Benito Pérez Galdós, que menciona esta botica en sus Episodios nacionales. ');
INSERT INTO `comercios` ( `visitas`,`likes`,`actividad`, `aparicion`, `cp`, `create_at`, `direccion`, `facebook`, `lat`, `lng`, `nombre`, `parrafo_one`,  `resumen`, `telefono`,`img`,`img1`,`img2`,`parrafo_two`) VALUES ('1','0','restaurantes', '1825', '28034 Madrid', '2019-11-01', 'Calle de nuestra señora de Valverde, 119','https://www.facebook.com/Restaurante-Casa-Pedro-2028879920670208/?__tn__=%2Cd%2CP-R&eid=ARDT2EBWUga4wWjXnyMhLghn-83KVCV8LwBF0jy48giUTTocM3TgcK5ZMO2jp7Vbg4Dz6AANh9rbaq6q', '40.497525', '-3.687061', 'Restaurante  Casa Pedro', ' Es uno de los rincones gastronómicos de la villa, que ha sabido mantener en el tiempo los sabores de la vieja cocina castellana, y madrileña después, es Casa Pedro.', 'Madrid, por su situación geográfica, siempre ha sido un sitio de paso con buenos establecimientos para hacer una alto y comer rico. Con el crecimiento de la región, las carreteras nacionales se han convertido en las calles centrales de las ciudades y han sido sustituidas por autovías que cruzan la capital casi sin enterarse.', '913664686','casaPedro1.jpg','5casaPedro1.jpg','casaPedro3.jpg',  'Con su impecable chaqueta blanca y una sonrisa de oreja a oreja, Pedro Guiñales recibe a todo el que para en Casa Pedro. La misma cordialidad que su hija Irene practica de manera natural con los clientes, muchos amigos ya de una casa que lleva desde principios del siglo XVIII reconfortando a viajeros y comerciantes ávidos de un suculento plato con el que celebrar una transacción satisfactoria o hacer más llevadero el camino. "Antes nadie comía fuera de casa, sólo los que viajaban. Estaba en la carretera de Fuencarral a El Pardo y la gente paraba a hacer noche aquí en mil setecientos y pico. Mucho más tarde, mi abuela dió una comida a Alfonso XIIIcuando iba al tiro de Cantoblanco", explica Guiñales, que es la séptima generación al frente del negocio familiar y muchos años después atendió al Rey Juan Carlos. ');

INSERT INTO comentarios (`comentario`, `email`, `fecha`, `id_comercio`, `nombre`,`contestacion`) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. ', 'maria@gmail.com', '2019-10-20', '1', 'María','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat');
INSERT INTO comentarios (`comentario`, `email`, `fecha`, `id_comercio`, `nombre`) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. ', 'nieves@gmail.com', '2019-10-20', '1', 'Nieves');
INSERT INTO comentarios (`comentario`, `email`, `fecha`, `id_comercio`, `nombre`,`contestacion`) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. ', 'maite@gmail.com', '2019-10-21', '1', 'Maite','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua');
INSERT INTO comentarios (`comentario`, `email`, `fecha`, `id_comercio`, `nombre`) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. ', 'nuria@gmail.com', '2019-10-22', '1', 'Nuria');
INSERT INTO comentarios (`comentario`, `email`, `fecha`, `id_comercio`, `nombre`) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. ', 'miriam@gmail.com', '2019-11-20', '1', 'Miriam');
INSERT INTO comentarios (`comentario`, `email`, `fecha`, `id_comercio`, `nombre`) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. ', 'paco@gmail.com', '2019-11-20', '1', 'Paco');
INSERT INTO comentarios (`comentario`, `email`, `fecha`, `id_comercio`, `nombre`) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. ', 'ana@gmail.com', '2019-12-20', '1', 'Ana');
INSERT INTO comentarios (`comentario`, `email`, `fecha`, `id_comercio`, `nombre`,`contestacion`) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. ', 'maria@gmail.com', '2019-10-20', '2', 'María','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat');
INSERT INTO comentarios (`comentario`, `email`, `fecha`, `id_comercio`, `nombre`) VALUES ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. ', 'maria@gmail.com', '2019-11-20', '2', 'Eva');




INSERT INTO `roles` (nombre) VALUES ('ROLE_USER');
INSERT INTO `roles` (nombre) VALUES ('ROLE_ADMIN');

INSERT INTO `usuarios_roles` (usuario_id, rol_id) VALUES (1, 1);,
INSERT INTO `usuarios_roles` (usuario_id, rol_id) VALUES (2, 2);
INSERT INTO `usuarios_roles` (usuario_id, rol_id) VALUES (2, 1);